import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const frontendRoot = resolve(projectRoot, "custom_components/water_accounting/frontend");
const sourceRoot = resolve(frontendRoot, "src");
const target = resolve(frontendRoot, "water-accounting-panel.js");

const [zoomSource, coreSource, cssSource] = await Promise.all([
  readFile(resolve(sourceRoot, "zoom-controller.js"), "utf8"),
  readFile(resolve(sourceRoot, "water-accounting-panel-core.js"), "utf8"),
  readFile(resolve(sourceRoot, "styles.css"), "utf8"),
]);

const marker = 'const WATER_CSS = "__WATER_ACCOUNTING_CSS__";';
if (!coreSource.includes(marker)) {
  throw new Error("CSS marker is missing from the frontend core");
}

const hydratedCore = coreSource.replace(
  marker,
  `const WATER_CSS = ${JSON.stringify(cssSource.trim() + "\n")};`,
);
const banner = "/* NikaS Water Accounting UI v0.1.1 · generated by scripts/build.mjs */\n";
const bundle = banner + zoomSource.trim() + "\n\n" + hydratedCore.trim() + "\n";

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== bundle) {
    throw new Error("Production bundle is not synchronized; run node scripts/build.mjs");
  }
  process.stdout.write(`Bundle is synchronized: ${target}\n`);
} else {
  await writeFile(target, bundle, "utf8");
  process.stdout.write(`Built ${target}\n`);
}
