import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const frontendRoot = resolve(projectRoot, "custom_components/water_accounting/frontend");
const sourceRoot = resolve(frontendRoot, "src");
const target = resolve(frontendRoot, "water-accounting-panel.js");
const shellPath = "templates/shell_v2/nikas-specialized-shell.js";

const [shellSource, zoomSource, coreSource, cssSource] = await Promise.all([
  readFile(resolve(projectRoot, shellPath), "utf8"),
  readFile(resolve(sourceRoot, "zoom-controller.js"), "utf8"),
  readFile(resolve(sourceRoot, "water-accounting-panel-core.js"), "utf8"),
  readFile(resolve(sourceRoot, "styles.css"), "utf8"),
]);

const marker = 'const WATER_CSS = "__WATER_ACCOUNTING_CSS__";';
if (!coreSource.includes(marker)) {
  throw new Error("CSS marker is missing from the frontend core");
}

const hydratedCore = coreSource.replace(
  marker,
  `// BEGIN custom_components/water_accounting/frontend/src/styles.css\nconst WATER_CSS = ${JSON.stringify(cssSource.trim() + "\n")};\n// END custom_components/water_accounting/frontend/src/styles.css`,
);
const banner = "/* NikaS Water Accounting UI v0.1.5 · generated by scripts/build.mjs */\n";
const bundle = banner
  + `// BEGIN ${shellPath}\n${shellSource.trim()}\n// END ${shellPath}\n\n`
  + `// BEGIN custom_components/water_accounting/frontend/src/zoom-controller.js\n${zoomSource.trim()}\n// END custom_components/water_accounting/frontend/src/zoom-controller.js\n\n`
  + `// BEGIN custom_components/water_accounting/frontend/src/water-accounting-panel-core.js\n${hydratedCore.trim()}\n// END custom_components/water_accounting/frontend/src/water-accounting-panel-core.js\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== bundle) {
    throw new Error("Production bundle is not synchronized; run node scripts/build.mjs");
  }
  process.stdout.write(`Bundle is synchronized: ${target}\n`);
} else {
  await writeFile(target, bundle, "utf8");
  process.stdout.write(`Built ${target}\n`);
}
